print("Introduce un valor: ")
a = int(input())
print("Introduce un valor: ")
b = int(input())
print("Introduce un valor: ")
c = int(input())
print("Introduce un valor: ")
d = int(input())
print("Valores introducidos: ", a, b, c, d)